In [1]:
# Imports
import pandas as pd
import pandas_profiling

In [2]:
# Load data set
data = pd.read_excel('marital_satisfaction_data.xlsx')

In [3]:
# Notes for cleanup
# convert categorical vars
# clear useless rows X
# what to do with questions as col name? X

In [4]:
data = data.drop(index=[1])

In [5]:
data = data.drop(index=[0])

In [6]:
col_names = pd.read_csv('col_names.csv')

In [7]:
col_names = list(col_names)

In [8]:
data.columns = col_names

In [9]:
data.head()

,country,sex,age,marriage_duration_years,num_children_total,num_children_inhome,edu_level,material_situation,religion,religiosity,...,spouse_satisfaction,relationship_satisfaction,natl_pride_in_parents,natl_pride_in_children,natl_aging_parents_live_with_children,natl_children_live_at_home_marraige,indv_pride_in_parents,indv_pride_in_children,indv_aging_parents_live_with_children,indv_children_live_at_home_marraige
2,Brazil,1.0,21.0,2.0,0.0,0.0,5.0,3.0,1.0,4.0,...,7.0,7.0,1,1.0,1.0,1.0,1,1.0,1.0,1.0
3,Brazil,1.0,29.0,3.0,1.0,0.0,5.0,3.0,1.0,6.0,...,6.0,6.0,2,1.0,1.0,1.0,1,1.0,1.0,1.0
4,Brazil,1.0,30.0,7.0,0.0,0.0,5.0,3.0,1.0,4.0,...,7.0,7.0,2,1.0,2.0,1.0,1,1.0,1.0,1.0
5,Brazil,1.0,30.0,7.0,1.0,1.0,5.0,3.0,1.0,6.0,...,6.0,6.0,3,1.0,1.0,2.0,1,1.0,1.0,1.0
6,Brazil,1.0,28.0,9.0,0.0,0.0,4.0,2.0,1.0,5.0,...,6.0,7.0,3,2.0,3.0,2.0,1,1.0,1.0,1.0

In [10]:
data = data.reset_index()

In [11]:
# Only null values are in religion?

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7178 entries, 0 to 7177
Data columns (total 32 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   index                                  7178 non-null   int64
 1   country                                7178 non-null   object
 2   sex                                    7178 non-null   float64
 3   age                                    7178 non-null   float64
 4   marriage_duration_years                7178 non-null   float64
 5   num_children_total                     7178 non-null   float64
 6   num_children_inhome                    7178 non-null   float64
 7   edu_level                              7178 non-null   float64
 8   material_situation                     7178 non-null   float64
 9   religion                               7092 non-null   float64
 10  religiosity                            7178 non-null   float64
 11  pension                                7178 non-null   float64
 12  enjoy_spouse_company                   7178 non-null   float64
 13  happiness                              7178 non-null   float64
 14  spouse_attraction                      7178 non-null   float64
 15  spouse_enjoy_doing_things_together     7178 non-null   float64
 16  spouse_enjoy_cuddling                  7178 non-null   float64
 17  spouse_respect                         7178 non-null   float64
 18  spouse_pride                           7178 non-null   float64
 19  spouse_romance                         7178 non-null   float64
 20  spouse_love                            7178 non-null   float64
 21  marital_satisfaction                   7178 non-null   float64
 22  spouse_satisfaction                    7178 non-null   float64
 23  relationship_satisfaction              7178 non-null   float64
 24  natl_pride_in_parents                  7178 non-null   object
 25  natl_pride_in_children                 7178 non-null   float64
 26  natl_aging_parents_live_with_children  7178 non-null   float64
 27  natl_children_live_at_home_marraige    7178 non-null   float64
 28  indv_pride_in_parents                  7178 non-null   object
 29  indv_pride_in_children                 7178 non-null   float64
 30  indv_aging_parents_live_with_children  7178 non-null   float64
 31  indv_children_live_at_home_marraige    7178 non-null   float64
dtypes: float64(28), int64(1), object(3)
memory usage: 1.8+ MB

In [12]:
globe_survey_dict = {1:"Strongly agree",2:"Agree somewhat",3:"Agree slightly",4:"Neither agree nor disagree",5:"Disagree slightly",6:"Disagree somewhat",7:"Disagree strongly"}

In [13]:
globe_survey_cols = list(data.columns[24:])

In [14]:
data[globe_survey_cols] = data[globe_survey_cols].replace(globe_survey_dict)

In [15]:
mrq_dict = {1:"Yes",2:"Rather yes",3:"Neither yes or no",4:"Rather no",5:"No"}

In [16]:
mrq_cols = list(data.columns[12:21])

In [17]:
data[mrq_cols] = data[mrq_cols].replace(mrq_dict)

In [18]:
data['sex'] = data['sex'].replace({1:"Male",2:"Female"})

In [19]:
data.head()

,index,country,sex,age,marriage_duration_years,num_children_total,num_children_inhome,edu_level,material_situation,religion,...,spouse_satisfaction,relationship_satisfaction,natl_pride_in_parents,natl_pride_in_children,natl_aging_parents_live_with_children,natl_children_live_at_home_marraige,indv_pride_in_parents,indv_pride_in_children,indv_aging_parents_live_with_children,indv_children_live_at_home_marraige
0,2,Brazil,Male,21.0,2.0,0.0,0.0,5.0,3.0,1.0,...,7.0,7.0,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree
1,3,Brazil,Male,29.0,3.0,1.0,0.0,5.0,3.0,1.0,...,6.0,6.0,Agree somewhat,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree
2,4,Brazil,Male,30.0,7.0,0.0,0.0,5.0,3.0,1.0,...,7.0,7.0,Agree somewhat,Strongly agree,Agree somewhat,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree
3,5,Brazil,Male,30.0,7.0,1.0,1.0,5.0,3.0,1.0,...,6.0,6.0,Agree slightly,Strongly agree,Strongly agree,Agree somewhat,Strongly agree,Strongly agree,Strongly agree,Strongly agree
4,6,Brazil,Male,28.0,9.0,0.0,0.0,4.0,2.0,1.0,...,6.0,7.0,Agree slightly,Agree somewhat,Agree slightly,Agree somewhat,Strongly agree,Strongly agree,Strongly agree,Strongly agree

In [21]:
data['religion'] = data['religion'].replace({1:"Protestant",2:"Catholic",3:"Jewish",4:"Muslim",5:"Buddhist",6:"None",7:"Jehovah",8:"Evangelic",9:"Spiritualism",10:"Other",11:"Orthodox",12:"Hindu"})

In [23]:
data['edu_level'] = data['edu_level'].replace({1:"No formal education",2:"Primary school",3:"Secondary school",4:"High school or technical school",5:"Bachelors or Masters degree"})

In [25]:
data['pension'] = data['pension'].replace(globe_survey_dict)

In [26]:
data['material_situation'] = data['material_situation'].replace({1:"Much better than average",2:"Better than average",3:"Average",4:"Worse than average",5:"Much worse than average"})

In [27]:
data.head()

,index,country,sex,age,marriage_duration_years,num_children_total,num_children_inhome,edu_level,material_situation,religion,...,spouse_satisfaction,relationship_satisfaction,natl_pride_in_parents,natl_pride_in_children,natl_aging_parents_live_with_children,natl_children_live_at_home_marraige,indv_pride_in_parents,indv_pride_in_children,indv_aging_parents_live_with_children,indv_children_live_at_home_marraige
0,2,Brazil,Male,21.0,2.0,0.0,0.0,Bachelors or Masters degree,Average,Protestant,...,7.0,7.0,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree
1,3,Brazil,Male,29.0,3.0,1.0,0.0,Bachelors or Masters degree,Average,Protestant,...,6.0,6.0,Agree somewhat,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree
2,4,Brazil,Male,30.0,7.0,0.0,0.0,Bachelors or Masters degree,Average,Protestant,...,7.0,7.0,Agree somewhat,Strongly agree,Agree somewhat,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree
3,5,Brazil,Male,30.0,7.0,1.0,1.0,Bachelors or Masters degree,Average,Protestant,...,6.0,6.0,Agree slightly,Strongly agree,Strongly agree,Agree somewhat,Strongly agree,Strongly agree,Strongly agree,Strongly agree
4,6,Brazil,Male,28.0,9.0,0.0,0.0,High school or technical school,Better than average,Protestant,...,6.0,7.0,Agree slightly,Agree somewhat,Agree slightly,Agree somewhat,Strongly agree,Strongly agree,Strongly agree,Strongly agree